import AppKit
import ConsoleKit
import DeskArt
import DeskView
import FakeSources
import Foundation
import SwiftUI

// A development tool, never shipped: renders the reference SwiftUI desk (a tagged copy of
// Mac Command Center's PK4Skin, with SKALA-2000's plate wording) and writes
//
//   layout   → Sources/DeskArt/Generated/LayoutData.swift and docs/layout.json: every
//              primitive of the desk and its frame in desk units, measured, not guessed.
//   goldens  → PNG renders of the desk in its states, to compare the new renderer against.
//
//   swift run DeskReference layout
//   swift run DeskReference goldens <folder> [scale]

@MainActor
enum Reference {

    static let root = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()

    /// The scripted day up to `hours`, through the real model, as the reference renders did.
    static func model(atHour hours: Double) -> (ConsoleModel, ManualClock) {
        let clock = ManualClock()
        let model = ConsoleModel(clock: clock, store: MemoryConsoleStore(), log: MemoryConsoleLog())
        var day = FakeDay(start: clock.now)
        while day.elapsed < hours * 3600 {
            let readings = day.step()
            clock.now = day.now
            model.ingest(readings)
            model.advance()
        }
        clock.advance(by: 1)
        model.advance()
        return (model, clock)
    }

    static func themed<V: View>(_ view: V, night: Bool, finish: Finish) -> some View {
        view
            .environment(\.pk4, PK4Palette(night: night))
            .environment(\.pk4Finish, finish)
            .environment(\.colorScheme, night ? .dark : .light)
    }

    // MARK: Layout

    struct Entry: Codable {
        var kind: String
        var id: String
        var info: [String: String]
        var x: Double
        var y: Double
        var w: Double
        var h: Double
    }

    final class Collector {
        var entries: [Entry] = []
    }

    static func layout() throws {
        let (model, _) = model(atHour: 1.1)
        let collector = Collector()
        let desk = PK4Desk(snapshot: model.snapshot)
            .frame(width: PK4Size.deskWidth, height: PK4Size.deskHeight)
            .overlayPreferenceValue(DeskMarks.self) { marks in
                GeometryReader { proxy in
                    let _ = {
                        collector.entries = marks.map { mark in
                            let r = proxy[mark.anchor]
                            func q(_ v: CGFloat) -> Double { (Double(v) * 1000).rounded() / 1000 }
                            return Entry(
                                kind: mark.kind, id: mark.id, info: mark.info, x: q(r.minX),
                                y: q(r.minY), w: q(r.width), h: q(r.height))
                        }
                    }()
                    Color.clear
                }
            }
        let renderer = ImageRenderer(content: themed(desk, night: false, finish: .greyGreen))
        renderer.scale = 2  // layout rounds to the pixel grid: half a unit, as on a Retina display
        _ = renderer.cgImage
        let entries = collector.entries
        guard !entries.isEmpty else { throw Failure("no marks were collected") }

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let json = try encoder.encode(entries)
        try json.write(to: root.appendingPathComponent("docs/layout.json"))

        // The same table compiled into DeskArt, so the app needs no resource bundle.
        var compact = JSONEncoder()
        compact = JSONEncoder()
        compact.outputFormatting = [.sortedKeys]
        let line = String(decoding: try compact.encode(entries), as: UTF8.self)
        let swift = """
            // Generated by `swift run DeskReference layout` from the reference SwiftUI desk.
            // Do not edit: change the reference and run it again.

            // swift-format-ignore-file
            extension DeskLayout {
                static let json = #\"\"\"
            \(line)
            \"\"\"#
            }

            """
        let folder = root.appendingPathComponent("Sources/DeskArt/Generated")
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        try swift.write(
            to: folder.appendingPathComponent("LayoutData.swift"), atomically: true, encoding: .utf8
        )
        var kinds: [String: Int] = [:]
        for entry in entries { kinds[entry.kind, default: 0] += 1 }
        print(
            "\(entries.count) primitives:",
            kinds.sorted { $0.key < $1.key }.map { "\($0.key) \($0.value)" }.joined(separator: ", ")
        )
    }

    // MARK: Goldens

    static func render<V: View>(_ view: V, _ name: String, scale: CGFloat, folder: URL) throws {
        let renderer = ImageRenderer(content: view)
        renderer.scale = scale
        guard let image = renderer.cgImage else { throw Failure("render failed: \(name)") }
        let rep = NSBitmapImageRep(cgImage: image)
        guard let png = rep.representation(using: .png, properties: [:]) else {
            throw Failure("encode failed: \(name)")
        }
        try png.write(to: folder.appendingPathComponent(name))
        print("wrote \(name) \(image.width)×\(image.height)")
    }

    static func goldens(folder: URL, scale: CGFloat) throws {
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let (model, clock) = model(atHour: 1.1)
        func desk(
            _ night: Bool = false, _ finish: Finish = .greyGreen, _ s: ConsoleSnapshot
        ) -> some View {
            themed(
                PK4Desk(snapshot: s).frame(width: PK4Size.deskWidth, height: PK4Size.deskHeight),
                night: night, finish: finish)
        }
        let live = model.snapshot
        try render(desk(false, .greyGreen, live), "day.png", scale: scale, folder: folder)
        try render(desk(true, .greyGreen, live), "night.png", scale: scale, folder: folder)
        // The static art alone: every lamp dark, no digits, needles on zero, no text on the
        // paper. What the new renderer bakes into its background.
        var dark = ConsoleSnapshot()
        dark.mains = true
        for id in PK4.nixies.keys { dark.nixies[id] = NixieFormat.dark(PK4.nixies[id]!) }
        dark.meters = [:]
        for night in [false, true] {
            for finish in Finish.allCases {
                var s = dark
                s.finish = finish
                try render(
                    desk(night, finish, s),
                    "static-\(night ? "night" : "day")-\(finish.rawValue).png",
                    scale: scale, folder: folder)
            }
        }
        // Everything lit: what the lit sprites must match.
        model.send(.press(PK4.lampTest))
        try render(
            desk(false, .greyGreen, model.snapshot), "lamp-test-day.png", scale: scale,
            folder: folder)
        try render(
            desk(true, .greyGreen, model.snapshot), "lamp-test-night.png", scale: scale,
            folder: folder)
        model.send(.release(PK4.lampTest))
        clock.advance(by: 2)
        model.advance()
        model.send(.mains(false))
        try render(
            desk(false, .greyGreen, model.snapshot), "mains-off.png", scale: scale, folder: folder)
    }

    struct Failure: Error, CustomStringConvertible {
        var description: String
        init(_ description: String) { self.description = description }
    }
}

MainActor.assumeIsolated {
    PK4Type.register()
    for name in [
        "BarlowCondensed-SemiBold", "BarlowCondensed-Bold", "Dosis-SemiBold", "NixieOne-Regular",
        "PermanentMarker-Regular", "Caveat-Regular", "CourierNewPSMT",
    ] where NSFont(name: name, size: 12) == nil {
        print("warning: font missing:", name)
    }
    let arguments = CommandLine.arguments.dropFirst()
    do {
        switch arguments.first {
        case "layout":
            try Reference.layout()
        case "goldens":
            let folder = URL(fileURLWithPath: arguments.dropFirst().first ?? "renders/goldens")
            let scale = arguments.dropFirst(2).first.flatMap { Double($0) }.map { CGFloat($0) } ?? 1
            try Reference.goldens(folder: folder, scale: scale)
        case "compare":
            let goldens = URL(fileURLWithPath: arguments.dropFirst().first ?? "renders/goldens")
            let out = URL(fileURLWithPath: arguments.dropFirst(2).first ?? "renders/compare")
            let scale = arguments.dropFirst(3).first.flatMap { Double($0) }.map { CGFloat($0) } ?? 1
            try Compare.run(
                goldens: goldens, out: out, scale: scale, only: arguments.dropFirst(4).first)
        case "align":
            let goldens = URL(fileURLWithPath: arguments.dropFirst().first ?? "renders/goldens")
            let scale = arguments.dropFirst(2).first.flatMap { Double($0) }.map { CGFloat($0) } ?? 1
            let kinds = Array(arguments.dropFirst(3))
            try Compare.align(goldens: goldens, scale: scale, kinds: kinds)
        case "sweep":
            let goldens = URL(fileURLWithPath: arguments.dropFirst().first ?? "renders/goldens2")
            let scale = arguments.dropFirst(2).first.flatMap { Double($0) }.map { CGFloat($0) } ?? 2
            try Compare.sweepBaselines(goldens: goldens, scale: scale)
        case "shadows":
            let goldens = URL(fileURLWithPath: arguments.dropFirst().first ?? "renders/goldens")
            let scale = arguments.dropFirst(2).first.flatMap { Double($0) }.map { CGFloat($0) } ?? 1
            try Compare.sweepShadows(goldens: goldens, scale: scale)
        case "test-goldens":
            // Half-size JPEGs of the reference, checked in for DeskTests' golden tests. Rendered
            // at full size and averaged down two by two: rendered at half size, SwiftUI would
            // snap its layout to a two-unit grid and the goldens would be off.
            let folder = Reference.root.appendingPathComponent("Tests/DeskTests/Goldens")
            let scratch = FileManager.default.temporaryDirectory.appendingPathComponent(
                "skala-goldens")
            try Reference.goldens(folder: scratch, scale: 1)
            try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
            for name in ["day", "night", "lamp-test-day", "lamp-test-night", "mains-off"] {
                guard let full = Compare.load(scratch.appendingPathComponent("\(name).png")),
                    let image = DeskImages.halved(full)
                else { continue }
                let rep = NSBitmapImageRep(cgImage: image)
                let jpeg = rep.representation(using: .jpeg, properties: [.compressionFactor: 0.92])!
                try jpeg.write(to: folder.appendingPathComponent("\(name).jpg"))
                print("wrote \(name).jpg \(jpeg.count / 1024) KB")
            }
        case "live":
            let goldens = URL(fileURLWithPath: arguments.dropFirst().first ?? "renders/goldens")
            let out = URL(fileURLWithPath: arguments.dropFirst(2).first ?? "renders/live")
            let scale = arguments.dropFirst(3).first.flatMap { Double($0) }.map { CGFloat($0) } ?? 1
            try Compare.live(goldens: goldens, out: out, scale: scale)
        case "seams":
            ArtSet.bandCount = 1
            let one = Compare.Pixels(ArtSet.renderBackground(style: ArtStyle(), scale: 1))
            ArtSet.bandCount = 8
            let eight = Compare.Pixels(ArtSet.renderBackground(style: ArtStyle(), scale: 1))
            var rows: [Int: Int] = [:]
            for y in 0..<one.height {
                for x in 0..<one.width {
                    let p = one.at(x, y), q = eight.at(x, y)
                    let d = abs(p.0 - q.0) + abs(p.1 - q.1) + abs(p.2 - q.2)
                    if d > 6 { rows[y, default: 0] += 1 }
                }
            }
            var columns: [Int: Int] = [:]
            for y in [260, 300, 500, 900, 1400] {
                for x in 0..<one.width {
                    let p = one.at(x, y), q = eight.at(x, y)
                    if abs(p.0 - q.0) + abs(p.1 - q.1) + abs(p.2 - q.2) > 6 {
                        columns[x, default: 0] += 1
                    }
                }
            }
            print("columns that differ:", columns.keys.sorted())
            print(
                "rows that differ:",
                rows.sorted { $0.key < $1.key }.map { "\($0.key):\($0.value)" }.joined(
                    separator: " "))
        case "states":
            // End states the reference cannot show (its guards lift by animation), drawn by
            // the real layer tree for a look.
            let out = URL(fileURLWithPath: arguments.dropFirst().first ?? "renders/states")
            try FileManager.default.createDirectory(at: out, withIntermediateDirectories: true)
            let (model, clock) = Reference.model(atHour: 1.1)
            model.send(.guard(PK4.f12, open: true))
            model.send(.key(PK4.f12, armed: true))
            model.send(.press(PK4.f12))
            for _ in 0..<2 { model.send(.selectorStep(1)) }
            clock.advance(by: 0.5)
            model.advance()
            var s = model.snapshot
            s.pencils[2] = "Review root"
            let image = DeskPrinter.image(s, style: ArtStyle(), scale: 1)!
            try Compare.write(image, out.appendingPathComponent("guards-up.png"))
            model.send(.release(PK4.f12))
            model.send(.mains(false))
            clock.advance(by: 1)
            model.advance()
            try Compare.write(
                DeskPrinter.image(model.snapshot, style: ArtStyle(night: true), scale: 1)!,
                out.appendingPathComponent("mains-off-night.png"))
            print("wrote states")
        case "icon":
            // The app icon, every size the .icns needs, into Resources/AppIcon.iconset.
            let folder = Reference.root.appendingPathComponent("build/AppIcon.iconset")
            try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
            for (points, factor) in [
                (16, 1), (16, 2), (32, 1), (32, 2), (128, 1), (128, 2), (256, 1), (256, 2),
                (512, 1), (512, 2),
            ] {
                let name =
                    factor == 1 ? "icon_\(points)x\(points).png" : "icon_\(points)x\(points)@2x.png"
                try Compare.write(
                    AppIcon.image(pixels: points * factor)!, folder.appendingPathComponent(name))
            }
            print("wrote \(folder.path)")
        case "timing":
            for scale in [1.024, 1.28, 1.6, 2.048] as [CGFloat] {
                let started = Date()
                let background = ArtSet.renderBackground(style: ArtStyle(), scale: scale)
                let middle = Date()
                let art = ArtSet.render(style: ArtStyle(night: true), scale: scale)!
                print(
                    String(
                        format:
                            "scale %.3f: background %.0f ms, whole set %.0f ms, %d sprites, %.0f MB",
                        scale, middle.timeIntervalSince(started) * 1000, art.renderSeconds * 1000,
                        art.sprites.count, Double(art.bytes) / 1_048_576), background.width)
            }
        case "probe":
            Probe.run()
        default:
            print(
                "usage: DeskReference layout | goldens <folder> [scale] | compare <goldens> <out> [scale] [only]"
            )
        }
    } catch {
        print("error:", error)
        exit(1)
    }
}
